name: CI Sentinel

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  discipline:
    name: Discipline Sentinel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # merge base must be reachable
      - uses: orieg/discipline@5db96e7c560450545e77b5086865687186939261 # v0.11.0
        with:
          version: v0.11.0
          fail_on_warnings: true

